// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using deportes.Infraestucture;

namespace deportes.Migrations
{
    [DbContext(typeof(DeportesDbContext))]
    [Migration("20201022233234_baseDeDatosbuena")]
    partial class baseDeDatosbuena
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("deportes.domain.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdProducto")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Idproducto")
                        .HasColumnName("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("deportes.domain.Producto", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<float>("Precio")
                        .HasColumnType("real")
                        .HasMaxLength(1500000);

                    b.HasKey("id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("deportes.domain.Categoria", b =>
                {
                    b.HasOne("deportes.domain.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto");
                });
#pragma warning restore 612, 618
        }
    }
}
